[package]
name = "qurious-shell"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "qurious-shell"
path = "src/bin/shell.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = { version = "13.0.0", features = ["derive"] }
